### ISSUE TITLE
Mediagoblin installation failes on RPi 2

### ISSUE THREAD

**Issue by khannover** [uboslinux/ubos-buildconfig#18]
[root@ubos-raspberry-pi2 ~]# ubos-admin createsite
App to run: mediagoblin
Downloading packages...
ERROR: FATAL: Failed to install package(s). Pacman says: warning: cannot resolve "libxslt", a dependency of "python2-lxml"
warning: cannot resolve "python2-lxml", a dependency of "mediagoblin"
error: failed to prepare transaction (could not satisfy dependencies)

-> libxslt currently only seems to exist on x86

**Comment by khannover** [comment]
Installing the missing dependency from a [Mirror](http://archlinuxarm.org/about/mirrors) solved the problem:

[root@ubos-raspberry-pi2 ~]# pacman -U http://de3.mirror.archlinuxarm.org/armv7h/extra/libxslt-1.1.28-3.1-armv7h.pkg.tar.xz

 libxslt-1.1.28-3.1-armv7h                   328.1 KiB  2.46M/s 00:00 [#######################################] 100%
 libxslt-1.1.28-3.1-armv7h.sig               543.0   B  0.00B/s 00:00 [#######################################] 100%
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) libxslt-1.1.28-3.1

Total Installed Size:  2.28 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                        [#######################################] 100%
(1/1) checking package integrity                                      [#######################################] 100%
(1/1) loading package files                                           [#######################################] 100%
(1/1) checking for file conflicts                                     [#######################################] 100%
(1/1) checking available disk space                                   [#######################################] 100%
(1/1) installing libxslt                                              [#######################################] 100%
[root@ubos-raspberry-pi2 ~]# pacman -S python2-lxml
resolving dependencies...
looking for conflicting packages...

Packages (1) python2-lxml-3.4.2-2

Total Download Size:   0.66 MiB
Total Installed Size:  2.87 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages ...
 python2-lxml-3.4.2-2-armv7h                 671.9 KiB  1179K/s 00:01 [#######################################] 100%
(1/1) checking keys in keyring                                        [#######################################] 100%
(1/1) checking package integrity                                      [#######################################] 100%
(1/1) loading package files                                           [#######################################] 100%
(1/1) checking for file conflicts                                     [#######################################] 100%
(1/1) checking available disk space                                   [#######################################] 100%
(1/1) installing python2-lxml                                         [#######################################] 100%
Optional dependencies for python2-lxml
    python2-beautifulsoup3: support for parsing not well formed HTML
    python-lxml-docs: offline docs
[root@ubos-raspberry-pi2 ~]# ubos-admin createsite
App to run: mediagoblin
Downloading packages...
[...]
Deploying...

**Comment by jernst** [comment]
libxslt is in extra.json; not sure yet why it wasn't put into the distro.
