### ISSUE TITLE
VirtualBox missing package

### ISSUE THREAD

**Issue by jernst** [uboslinux/ubos-buildconfig#29]
Need to preinstall `virtualbox-guest-modules-arch` otherwise kernel modules cannot be found. Can probably get rid of DKMS package from pre-install (should remain in repo). Also need `linux-headers` in the repo otherwise DKMS packages cannot be rebuilt.

In the meantime, a workaround:
```
curl -O http://mirror.clarkson.edu/archlinux/community/os/x86_64/virtualbox-guest-modules-arch-5.1.8-1-x86_64.pkg.tar.xz
curl -O http://mirror.clarkson.edu/archlinux/community/os/x86_64/virtualbox-guest-modules-arch-5.1.8-1-x86_64.pkg.tar.xz.sig
pacman -Rdd virtualbox-guest-dkms
pacman -U virtualbox-guest-modules-arch
```

**Comment by julianfoad** [comment]
That workaround works for me, if I amend the last line to include the full filename, i.e. "pacman -U virtualbox-guest-modules-arch-5.1.8-1-x86_64.pkg.tar.xz". By "works" I mean that "systemctl is-system-running" previously reported "degraded" but now, after doing that and rebooting, reports "running".

(I am using ubos_yellow_vbox-x86_64_20161109-220216.vmdk, in Virtualbox version "5.0.24_Ubuntu r108355" on an Ubuntu 16.04 host.)

**Comment by jernst** [comment]
Operator error, worked just fine, one should just simply test the correct virtual machine.
