### ISSUE TITLE
Target code-is-current does not work when using same external hard drive on multiple devices

### ISSUE THREAD

**Issue by uboslinux** [uboslinux/ubos-buildconfig#5]
This line:
    ( cd "$p"; ls -d _pkg_ > /dev/null 2>&1 || ( env -i makepkg -c -f && sudo pacman -U --noconfirm _pkg_ ))
means code does not get installed if there is a local pkg file, but that pkg file might have been built on a different device.

**Comment by jernst** [comment]
Not a use case any more.
