### ISSUE TITLE
Installing DNSChain and PowerDNS

### ISSUE THREAD

**Issue by jfeldis** [uboslinux/ubos-buildconfig#8]
The following packages are needed for UBOS to support DNSChain and PowerDNS for local blockchain DNS service.  this includes make and other tools needed to build pdns_recursor from source.  It would be helpful to have pdns_recursor available as a binary, the the build tools would not be needed.

automake	(1.15-1)
m4	(1.4.17-1)
diffutils	(3.3-2)
autoconf	(2.69-2)
bison	(3.0.4-1)
flex	(2.5.39-1)
libtool	(2.4.6-1)
libatomic_ops	(7.4.2-1)
gc	(7.4.2-2.1)
guile	(2.0.11-2)
make	(4.1-1)
ragel	(6.9-1)
pkg-config	(0.28-2)
icu	(54.1-1)
boost-libs	(1.57.0-3)
boost	(1.57.0-3)
postgresql-libs	(9.4.1-1)
lua	(5.2.3-1)
powerdns	(3.4.2-2)
nodejs	(0.12.0-5)
python	(3.4.3-1)
powerdns-recursor	(3.6.2-1)
idnkit	(1.0-3)
dnsutils	(9.9.2.P2-2)
curl	(7.40.0-1)
powerdns-recursor	(3.6.2-1)

**Comment by indiebox** [comment]
@jfeldis: What exactly needs the postgresql-libs? Is there a way to make it work with mysql/mariadb instead? Trying to avoid running more than one db on low-powered systems ...

**Comment by indiebox** [comment]
powerdns lists postgresql-libs, sqlite, libldap, and lua as required dependencies. That is strictly speaking not correct, and I filed a bug against the upstream package: https://bugs.archlinux.org/task/44218. Let's see what those guys will say.

**Comment by jfeldis** [comment]
ok.  I think we specifically just need pdns_recursor which i think is a subset of PowerDNS Server.  I installed the dependencies for the whole PowerDNS package, but then only built the recursor component, so it may or may not be needed.

**Comment by jernst** [comment]
@jfieldis: "The following packages are in conflict":

* libtool and libltdl

Also, which version of python do you need? There is now python2, which may or may not be what you want.

Please advise.

**Comment by jernst** [comment]
I'm going to close this, because (almost) all of those packages are here now. Let's create a separate issue with whatever is still missing.
